// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include "zcommoncrypto.h"

CCCryptorStatus CCCrypt(CCOperation, CCAlgorithm, CCOptions, const unsigned char*, size_t, const unsigned char*, const unsigned char*, size_t, unsigned char*, size_t, size_t*);
CCCryptorStatus CCCryptorCreate(CCOperation, CCAlgorithm, CCOptions, const unsigned char*, size_t, const unsigned char*, CCCryptorRef*);
CCCryptorStatus CCCryptorCreateWithMode(CCOperation, CCMode, CCAlgorithm, CCPadding, const unsigned char*, const unsigned char*, size_t, const unsigned char*, size_t, int, CCModeOptions, CCCryptorRef*);
CCCryptorStatus CCCryptorRelease(CCCryptorRef);
CCCryptorStatus CCCryptorReset(CCCryptorRef, const unsigned char*);
CCCryptorStatus CCCryptorUpdate(CCCryptorRef, const unsigned char*, size_t, unsigned char*, size_t, size_t*);
CCCryptorStatus CCKeyDerivationPBKDF(CCPBKDFAlgorithm, const char*, size_t, const uint8_t*, size_t, CCPseudoRandomAlgorithm, unsigned, uint8_t*, size_t);

CCCryptorStatus _mkcgo_CCCrypt(CCOperation _arg0, CCAlgorithm _arg1, CCOptions _arg2, const unsigned char* _arg3, size_t _arg4, const unsigned char* _arg5, const unsigned char* _arg6, size_t _arg7, unsigned char* _arg8, size_t _arg9, size_t* _arg10) {
	return CCCrypt(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10);
}

CCCryptorStatus _mkcgo_CCCryptorCreate(CCOperation _arg0, CCAlgorithm _arg1, CCOptions _arg2, const unsigned char* _arg3, size_t _arg4, const unsigned char* _arg5, CCCryptorRef* _arg6) {
	return CCCryptorCreate(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6);
}

CCCryptorStatus _mkcgo_CCCryptorCreateWithMode(CCOperation _arg0, CCMode _arg1, CCAlgorithm _arg2, CCPadding _arg3, const unsigned char* _arg4, const unsigned char* _arg5, size_t _arg6, const unsigned char* _arg7, size_t _arg8, int _arg9, CCModeOptions _arg10, CCCryptorRef* _arg11) {
	return CCCryptorCreateWithMode(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11);
}

CCCryptorStatus _mkcgo_CCCryptorRelease(CCCryptorRef _arg0) {
	return CCCryptorRelease(_arg0);
}

CCCryptorStatus _mkcgo_CCCryptorReset(CCCryptorRef _arg0, const unsigned char* _arg1) {
	return CCCryptorReset(_arg0, _arg1);
}

CCCryptorStatus _mkcgo_CCCryptorUpdate(CCCryptorRef _arg0, const unsigned char* _arg1, size_t _arg2, unsigned char* _arg3, size_t _arg4, size_t* _arg5) {
	return CCCryptorUpdate(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

CCCryptorStatus _mkcgo_CCKeyDerivationPBKDF(CCPBKDFAlgorithm _arg0, const char* _arg1, size_t _arg2, const uint8_t* _arg3, size_t _arg4, CCPseudoRandomAlgorithm _arg5, unsigned _arg6, uint8_t* _arg7, size_t _arg8) {
	return CCKeyDerivationPBKDF(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8);
}

