// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

//go:build go1.24 && !cmd_go_bootstrap

package commoncrypto

/*
#cgo noescape _mkcgo_CCCrypt
#cgo nocallback _mkcgo_CCCrypt
#cgo noescape _mkcgo_CCCryptorUpdate
#cgo nocallback _mkcgo_CCCryptorUpdate
*/
import "C"
