// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo

#include "textflag.h"
 
TEXT _mkcgo_CCCrypt_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCrypt(SB)
GLOBL   ·_mkcgo_CCCrypt_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCCrypt_trampoline_addr(SB)/8, $_mkcgo_CCCrypt_trampoline<>(SB)

TEXT _mkcgo_CCCryptorCreate_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorCreate(SB)
GLOBL   ·_mkcgo_CCCryptorCreate_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCCryptorCreate_trampoline_addr(SB)/8, $_mkcgo_CCCryptorCreate_trampoline<>(SB)

TEXT _mkcgo_CCCryptorCreateWithMode_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorCreateWithMode(SB)
GLOBL   ·_mkcgo_CCCryptorCreateWithMode_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCCryptorCreateWithMode_trampoline_addr(SB)/8, $_mkcgo_CCCryptorCreateWithMode_trampoline<>(SB)

TEXT _mkcgo_CCCryptorRelease_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorRelease(SB)
GLOBL   ·_mkcgo_CCCryptorRelease_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCCryptorRelease_trampoline_addr(SB)/8, $_mkcgo_CCCryptorRelease_trampoline<>(SB)

TEXT _mkcgo_CCCryptorReset_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorReset(SB)
GLOBL   ·_mkcgo_CCCryptorReset_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCCryptorReset_trampoline_addr(SB)/8, $_mkcgo_CCCryptorReset_trampoline<>(SB)

TEXT _mkcgo_CCCryptorUpdate_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorUpdate(SB)
GLOBL   ·_mkcgo_CCCryptorUpdate_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCCryptorUpdate_trampoline_addr(SB)/8, $_mkcgo_CCCryptorUpdate_trampoline<>(SB)

TEXT _mkcgo_CCKeyDerivationPBKDF_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCKeyDerivationPBKDF(SB)
GLOBL   ·_mkcgo_CCKeyDerivationPBKDF_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_CCKeyDerivationPBKDF_trampoline_addr(SB)/8, $_mkcgo_CCKeyDerivationPBKDF_trampoline<>(SB)

