// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo

#include "textflag.h"


#ifndef GOARCH_amd64
#ifndef GOARCH_arm64
#ifndef GOARCH_riscv64
#ifndef GOARCH_loong64
#ifndef GOARCH_mips64
#ifndef GOARCH_mips64le
#ifndef GOARCH_ppc64
#ifndef GOARCH_ppc64le
#ifndef GOARCH_sparc64
#define _GOPTRSIZE 4
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif


#ifndef _GOPTRSIZE
#define _GOPTRSIZE 8
#endif
TEXT _mkcgo_CCCrypt_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCrypt(SB)
GLOBL   ·_mkcgo_CCCrypt_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCCrypt_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCCrypt_trampoline<>(SB)

TEXT _mkcgo_CCCryptorCreate_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorCreate(SB)
GLOBL   ·_mkcgo_CCCryptorCreate_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCCryptorCreate_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCCryptorCreate_trampoline<>(SB)

TEXT _mkcgo_CCCryptorCreateWithMode_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorCreateWithMode(SB)
GLOBL   ·_mkcgo_CCCryptorCreateWithMode_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCCryptorCreateWithMode_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCCryptorCreateWithMode_trampoline<>(SB)

TEXT _mkcgo_CCCryptorRelease_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorRelease(SB)
GLOBL   ·_mkcgo_CCCryptorRelease_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCCryptorRelease_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCCryptorRelease_trampoline<>(SB)

TEXT _mkcgo_CCCryptorReset_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorReset(SB)
GLOBL   ·_mkcgo_CCCryptorReset_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCCryptorReset_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCCryptorReset_trampoline<>(SB)

TEXT _mkcgo_CCCryptorUpdate_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCCryptorUpdate(SB)
GLOBL   ·_mkcgo_CCCryptorUpdate_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCCryptorUpdate_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCCryptorUpdate_trampoline<>(SB)

TEXT _mkcgo_CCKeyDerivationPBKDF_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_CCKeyDerivationPBKDF(SB)
GLOBL   ·_mkcgo_CCKeyDerivationPBKDF_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA    ·_mkcgo_CCKeyDerivationPBKDF_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_CCKeyDerivationPBKDF_trampoline<>(SB)

