// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

package commoncrypto

const (
	KCCEncrypt CCOperation = 0
	KCCDecrypt CCOperation = 1
)

const (
	KCCModeCBC CCMode = 2
)

const (
	KCCOptionECBMode CCOptions = 2
)

const (
	KCCSuccess CCCryptorStatus = 0
)

const (
	KCCPBKDF2 CCPBKDFAlgorithm = 2
)

const (
	KCCPRFHmacAlgSHA1   CCPseudoRandomAlgorithm = 1
	KCCPRFHmacAlgSHA256 CCPseudoRandomAlgorithm = 3
	KCCPRFHmacAlgSHA384 CCPseudoRandomAlgorithm = 4
	KCCPRFHmacAlgSHA512 CCPseudoRandomAlgorithm = 5
)

const (
	KCCBlockSizeAES128 = 16
	KCCBlockSizeDES    = 8
)

const (
	CcNoPadding CCPadding = 0
)

const (
	KCCAlgorithmAES  CCAlgorithm = 0
	KCCAlgorithmDES  CCAlgorithm = 1
	KCCAlgorithm3DES CCAlgorithm = 2
	KCCAlgorithmRC4  CCAlgorithm = 4
)
