// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo && darwin

package cryptokit

import (
	"syscall"
	"unsafe"
	_ "unsafe"
)

// libcCallInfo is a structure used to pass parameters to the system call.
type libcCallInfo struct {
	fn     uintptr
	n      uintptr // number of parameters
	args   uintptr // parameters
	r1, r2 uintptr // return values
}

// libcCallN is a wrapper around the libc call with variable arguments.
//
//go:nosplit
func syscallN(fn uintptr, args ...uintptr) (r1, r2 uintptr, err syscall.Errno) {
	libcArgs := libcCallInfo{
		fn: fn,
		n:  uintptr(len(args)),
	}
	if libcArgs.n != 0 {
		libcArgs.args = uintptr(noescape(unsafe.Pointer(&args[0])))
	}
	syscallNRaw(unsafe.Pointer(&libcArgs))
	return libcArgs.r1, libcArgs.r2, 0
}

//go:nosplit
func noescape(p unsafe.Pointer) unsafe.Pointer {
	x := uintptr(p)
	return unsafe.Pointer(x ^ 0)
}

//go:noescape
func syscallNRaw(args unsafe.Pointer)
