// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

#ifndef MKCGO_H // only include this header once
#define MKCGO_H

#include <stddef.h>
#include <stdint.h>


typedef void* mkcgo_err_state;
mkcgo_err_state mkcgo_err_retrieve();
void mkcgo_err_free(mkcgo_err_state);

void _mkcgo_go_MD5(const uint8_t*, size_t, const uint8_t*);
void _mkcgo_go_SHA1(const uint8_t*, size_t, const uint8_t*);
void _mkcgo_go_SHA256(const uint8_t*, size_t, const uint8_t*);
void _mkcgo_go_SHA384(const uint8_t*, size_t, const uint8_t*);
void _mkcgo_go_SHA512(const uint8_t*, size_t, const uint8_t*);
void* _mkcgo_go_copyHMAC(int32_t, void*);
int _mkcgo_go_decryptAESGCM(const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t*);
int _mkcgo_go_encryptAESGCM(const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t, uint8_t*);
int _mkcgo_go_expandHKDF(int32_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t);
int _mkcgo_go_extractHKDF(int32_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t);
void _mkcgo_go_finalizeHMAC(int32_t, void*, uint8_t*);
void _mkcgo_go_freeHMAC(int32_t, void*);
void _mkcgo_go_generateKeyEd25519(uint8_t*);
int _mkcgo_go_hashBlockSize(int32_t);
void* _mkcgo_go_hashCopy(int32_t, void*);
void _mkcgo_go_hashFree(int32_t, void*);
void* _mkcgo_go_hashNew(int32_t);
void _mkcgo_go_hashReset(int32_t, void*);
int _mkcgo_go_hashSize(int32_t);
void _mkcgo_go_hashSum(int32_t, void*, uint8_t*);
void _mkcgo_go_hashWrite(int32_t, void*, const uint8_t*, int);
void* _mkcgo_go_initHMAC(int32_t, const uint8_t*, int);
int _mkcgo_go_newPrivateKeyEd25519FromSeed(uint8_t*, const uint8_t*);
int _mkcgo_go_newPublicKeyEd25519(uint8_t*, const uint8_t*);
int _mkcgo_go_signEd25519(const uint8_t*, const uint8_t*, size_t, uint8_t*);
void _mkcgo_go_updateHMAC(int32_t, void*, const uint8_t*, int);
int _mkcgo_go_verifyEd25519(const uint8_t*, const uint8_t*, size_t, const uint8_t*);

#endif // MKCGO_H
