// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include "zcryptokit.h"

void go_MD5(const uint8_t*, size_t, const uint8_t*);
void go_SHA1(const uint8_t*, size_t, const uint8_t*);
void go_SHA256(const uint8_t*, size_t, const uint8_t*);
void go_SHA384(const uint8_t*, size_t, const uint8_t*);
void go_SHA3_256(const uint8_t*, size_t, const uint8_t*);
void go_SHA3_384(const uint8_t*, size_t, const uint8_t*);
void go_SHA3_512(const uint8_t*, size_t, const uint8_t*);
void go_SHA512(const uint8_t*, size_t, const uint8_t*);
void* go_copyHMAC(int32_t, void*);
int go_decapsulateMLKEM1024(const uint8_t*, int, const uint8_t*, int, uint8_t*, int);
int go_decapsulateMLKEM768(const uint8_t*, int, const uint8_t*, int, uint8_t*, int);
int go_decryptAESGCM(const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t*);
int go_deriveEncapsulationKeyMLKEM1024(const uint8_t*, int, uint8_t*, int);
int go_deriveEncapsulationKeyMLKEM768(const uint8_t*, int, uint8_t*, int);
int go_encapsulateMLKEM1024(const uint8_t*, int, uint8_t*, int, uint8_t*, int);
int go_encapsulateMLKEM768(const uint8_t*, int, uint8_t*, int, uint8_t*, int);
int go_encryptAESGCM(const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t, uint8_t*);
int go_expandHKDF(int32_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t);
int go_extractHKDF(int32_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t);
void go_finalizeHMAC(int32_t, void*, uint8_t*);
void go_freeHMAC(int32_t, void*);
void go_generateKeyEd25519(uint8_t*);
int go_generateKeyMLKEM1024(uint8_t*, int);
int go_generateKeyMLKEM768(uint8_t*, int);
int go_generateKeyX25519(uint8_t*, int);
int go_hashBlockSize(int32_t);
void* go_hashCopy(int32_t, void*);
void go_hashFree(int32_t, void*);
void* go_hashNew(int32_t);
void go_hashReset(int32_t, void*);
int go_hashSize(int32_t);
void go_hashSum(int32_t, void*, uint8_t*);
void go_hashWrite(int32_t, void*, const uint8_t*, int);
void* go_initHMAC(int32_t, const uint8_t*, int);
int go_newPrivateKeyEd25519FromSeed(uint8_t*, const uint8_t*);
int go_newPublicKeyEd25519(uint8_t*, const uint8_t*);
int go_publicKeyX25519(uint8_t*, int);
int go_signEd25519(const uint8_t*, const uint8_t*, size_t, uint8_t*);
int go_supportsMLKEM(void);
int go_supportsSHA3(void);
void go_updateHMAC(int32_t, void*, const uint8_t*, int);
int go_verifyEd25519(const uint8_t*, const uint8_t*, size_t, const uint8_t*);
int go_x25519(const uint8_t*, int, const uint8_t*, int, uint8_t*, int);

void _mkcgo_go_MD5(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_MD5(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA1(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA1(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA256(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA256(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA384(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA384(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA3_256(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA3_256(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA3_384(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA3_384(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA3_512(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA3_512(_arg0, _arg1, _arg2);
}

void _mkcgo_go_SHA512(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2) {
	go_SHA512(_arg0, _arg1, _arg2);
}

void* _mkcgo_go_copyHMAC(int32_t _arg0, void* _arg1) {
	return go_copyHMAC(_arg0, _arg1);
}

int _mkcgo_go_decapsulateMLKEM1024(const uint8_t* _arg0, int _arg1, const uint8_t* _arg2, int _arg3, uint8_t* _arg4, int _arg5) {
	return go_decapsulateMLKEM1024(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int _mkcgo_go_decapsulateMLKEM768(const uint8_t* _arg0, int _arg1, const uint8_t* _arg2, int _arg3, uint8_t* _arg4, int _arg5) {
	return go_decapsulateMLKEM768(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int _mkcgo_go_decryptAESGCM(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2, size_t _arg3, const uint8_t* _arg4, size_t _arg5, const uint8_t* _arg6, size_t _arg7, const uint8_t* _arg8, size_t _arg9, uint8_t* _arg10, size_t* _arg11) {
	return go_decryptAESGCM(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11);
}

int _mkcgo_go_deriveEncapsulationKeyMLKEM1024(const uint8_t* _arg0, int _arg1, uint8_t* _arg2, int _arg3) {
	return go_deriveEncapsulationKeyMLKEM1024(_arg0, _arg1, _arg2, _arg3);
}

int _mkcgo_go_deriveEncapsulationKeyMLKEM768(const uint8_t* _arg0, int _arg1, uint8_t* _arg2, int _arg3) {
	return go_deriveEncapsulationKeyMLKEM768(_arg0, _arg1, _arg2, _arg3);
}

int _mkcgo_go_encapsulateMLKEM1024(const uint8_t* _arg0, int _arg1, uint8_t* _arg2, int _arg3, uint8_t* _arg4, int _arg5) {
	return go_encapsulateMLKEM1024(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int _mkcgo_go_encapsulateMLKEM768(const uint8_t* _arg0, int _arg1, uint8_t* _arg2, int _arg3, uint8_t* _arg4, int _arg5) {
	return go_encapsulateMLKEM768(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int _mkcgo_go_encryptAESGCM(const uint8_t* _arg0, size_t _arg1, const uint8_t* _arg2, size_t _arg3, const uint8_t* _arg4, size_t _arg5, const uint8_t* _arg6, size_t _arg7, uint8_t* _arg8, size_t _arg9, uint8_t* _arg10) {
	return go_encryptAESGCM(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10);
}

int _mkcgo_go_expandHKDF(int32_t _arg0, const uint8_t* _arg1, size_t _arg2, const uint8_t* _arg3, size_t _arg4, uint8_t* _arg5, size_t _arg6) {
	return go_expandHKDF(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6);
}

int _mkcgo_go_extractHKDF(int32_t _arg0, const uint8_t* _arg1, size_t _arg2, const uint8_t* _arg3, size_t _arg4, uint8_t* _arg5, size_t _arg6) {
	return go_extractHKDF(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6);
}

void _mkcgo_go_finalizeHMAC(int32_t _arg0, void* _arg1, uint8_t* _arg2) {
	go_finalizeHMAC(_arg0, _arg1, _arg2);
}

void _mkcgo_go_freeHMAC(int32_t _arg0, void* _arg1) {
	go_freeHMAC(_arg0, _arg1);
}

void _mkcgo_go_generateKeyEd25519(uint8_t* _arg0) {
	go_generateKeyEd25519(_arg0);
}

int _mkcgo_go_generateKeyMLKEM1024(uint8_t* _arg0, int _arg1) {
	return go_generateKeyMLKEM1024(_arg0, _arg1);
}

int _mkcgo_go_generateKeyMLKEM768(uint8_t* _arg0, int _arg1) {
	return go_generateKeyMLKEM768(_arg0, _arg1);
}

int _mkcgo_go_generateKeyX25519(uint8_t* _arg0, int _arg1) {
	return go_generateKeyX25519(_arg0, _arg1);
}

int _mkcgo_go_hashBlockSize(int32_t _arg0) {
	return go_hashBlockSize(_arg0);
}

void* _mkcgo_go_hashCopy(int32_t _arg0, void* _arg1) {
	return go_hashCopy(_arg0, _arg1);
}

void _mkcgo_go_hashFree(int32_t _arg0, void* _arg1) {
	go_hashFree(_arg0, _arg1);
}

void* _mkcgo_go_hashNew(int32_t _arg0) {
	return go_hashNew(_arg0);
}

void _mkcgo_go_hashReset(int32_t _arg0, void* _arg1) {
	go_hashReset(_arg0, _arg1);
}

int _mkcgo_go_hashSize(int32_t _arg0) {
	return go_hashSize(_arg0);
}

void _mkcgo_go_hashSum(int32_t _arg0, void* _arg1, uint8_t* _arg2) {
	go_hashSum(_arg0, _arg1, _arg2);
}

void _mkcgo_go_hashWrite(int32_t _arg0, void* _arg1, const uint8_t* _arg2, int _arg3) {
	go_hashWrite(_arg0, _arg1, _arg2, _arg3);
}

void* _mkcgo_go_initHMAC(int32_t _arg0, const uint8_t* _arg1, int _arg2) {
	return go_initHMAC(_arg0, _arg1, _arg2);
}

int _mkcgo_go_newPrivateKeyEd25519FromSeed(uint8_t* _arg0, const uint8_t* _arg1) {
	return go_newPrivateKeyEd25519FromSeed(_arg0, _arg1);
}

int _mkcgo_go_newPublicKeyEd25519(uint8_t* _arg0, const uint8_t* _arg1) {
	return go_newPublicKeyEd25519(_arg0, _arg1);
}

int _mkcgo_go_publicKeyX25519(uint8_t* _arg0, int _arg1) {
	return go_publicKeyX25519(_arg0, _arg1);
}

int _mkcgo_go_signEd25519(const uint8_t* _arg0, const uint8_t* _arg1, size_t _arg2, uint8_t* _arg3) {
	return go_signEd25519(_arg0, _arg1, _arg2, _arg3);
}

int _mkcgo_go_supportsMLKEM(void) {
	return go_supportsMLKEM();
}

int _mkcgo_go_supportsSHA3(void) {
	return go_supportsSHA3();
}

void _mkcgo_go_updateHMAC(int32_t _arg0, void* _arg1, const uint8_t* _arg2, int _arg3) {
	go_updateHMAC(_arg0, _arg1, _arg2, _arg3);
}

int _mkcgo_go_verifyEd25519(const uint8_t* _arg0, const uint8_t* _arg1, size_t _arg2, const uint8_t* _arg3) {
	return go_verifyEd25519(_arg0, _arg1, _arg2, _arg3);
}

int _mkcgo_go_x25519(const uint8_t* _arg0, int _arg1, const uint8_t* _arg2, int _arg3, uint8_t* _arg4, int _arg5) {
	return go_x25519(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

