// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo

#include "textflag.h"
 
TEXT _mkcgo_go_MD5_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_MD5(SB)
GLOBL   ·_mkcgo_go_MD5_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_MD5_trampoline_addr(SB)/8, $_mkcgo_go_MD5_trampoline<>(SB)

TEXT _mkcgo_go_SHA1_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_SHA1(SB)
GLOBL   ·_mkcgo_go_SHA1_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_SHA1_trampoline_addr(SB)/8, $_mkcgo_go_SHA1_trampoline<>(SB)

TEXT _mkcgo_go_SHA256_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_SHA256(SB)
GLOBL   ·_mkcgo_go_SHA256_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_SHA256_trampoline_addr(SB)/8, $_mkcgo_go_SHA256_trampoline<>(SB)

TEXT _mkcgo_go_SHA384_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_SHA384(SB)
GLOBL   ·_mkcgo_go_SHA384_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_SHA384_trampoline_addr(SB)/8, $_mkcgo_go_SHA384_trampoline<>(SB)

TEXT _mkcgo_go_SHA512_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_SHA512(SB)
GLOBL   ·_mkcgo_go_SHA512_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_SHA512_trampoline_addr(SB)/8, $_mkcgo_go_SHA512_trampoline<>(SB)

TEXT _mkcgo_go_copyHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_copyHMAC(SB)
GLOBL   ·_mkcgo_go_copyHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_copyHMAC_trampoline_addr(SB)/8, $_mkcgo_go_copyHMAC_trampoline<>(SB)

TEXT _mkcgo_go_decryptAESGCM_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_decryptAESGCM(SB)
GLOBL   ·_mkcgo_go_decryptAESGCM_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_decryptAESGCM_trampoline_addr(SB)/8, $_mkcgo_go_decryptAESGCM_trampoline<>(SB)

TEXT _mkcgo_go_encryptAESGCM_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_encryptAESGCM(SB)
GLOBL   ·_mkcgo_go_encryptAESGCM_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_encryptAESGCM_trampoline_addr(SB)/8, $_mkcgo_go_encryptAESGCM_trampoline<>(SB)

TEXT _mkcgo_go_expandHKDF_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_expandHKDF(SB)
GLOBL   ·_mkcgo_go_expandHKDF_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_expandHKDF_trampoline_addr(SB)/8, $_mkcgo_go_expandHKDF_trampoline<>(SB)

TEXT _mkcgo_go_extractHKDF_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_extractHKDF(SB)
GLOBL   ·_mkcgo_go_extractHKDF_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_extractHKDF_trampoline_addr(SB)/8, $_mkcgo_go_extractHKDF_trampoline<>(SB)

TEXT _mkcgo_go_finalizeHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_finalizeHMAC(SB)
GLOBL   ·_mkcgo_go_finalizeHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_finalizeHMAC_trampoline_addr(SB)/8, $_mkcgo_go_finalizeHMAC_trampoline<>(SB)

TEXT _mkcgo_go_freeHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_freeHMAC(SB)
GLOBL   ·_mkcgo_go_freeHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_freeHMAC_trampoline_addr(SB)/8, $_mkcgo_go_freeHMAC_trampoline<>(SB)

TEXT _mkcgo_go_generateKeyEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_generateKeyEd25519(SB)
GLOBL   ·_mkcgo_go_generateKeyEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_generateKeyEd25519_trampoline_addr(SB)/8, $_mkcgo_go_generateKeyEd25519_trampoline<>(SB)

TEXT _mkcgo_go_hashBlockSize_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashBlockSize(SB)
GLOBL   ·_mkcgo_go_hashBlockSize_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashBlockSize_trampoline_addr(SB)/8, $_mkcgo_go_hashBlockSize_trampoline<>(SB)

TEXT _mkcgo_go_hashCopy_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashCopy(SB)
GLOBL   ·_mkcgo_go_hashCopy_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashCopy_trampoline_addr(SB)/8, $_mkcgo_go_hashCopy_trampoline<>(SB)

TEXT _mkcgo_go_hashFree_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashFree(SB)
GLOBL   ·_mkcgo_go_hashFree_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashFree_trampoline_addr(SB)/8, $_mkcgo_go_hashFree_trampoline<>(SB)

TEXT _mkcgo_go_hashNew_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashNew(SB)
GLOBL   ·_mkcgo_go_hashNew_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashNew_trampoline_addr(SB)/8, $_mkcgo_go_hashNew_trampoline<>(SB)

TEXT _mkcgo_go_hashReset_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashReset(SB)
GLOBL   ·_mkcgo_go_hashReset_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashReset_trampoline_addr(SB)/8, $_mkcgo_go_hashReset_trampoline<>(SB)

TEXT _mkcgo_go_hashSize_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashSize(SB)
GLOBL   ·_mkcgo_go_hashSize_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashSize_trampoline_addr(SB)/8, $_mkcgo_go_hashSize_trampoline<>(SB)

TEXT _mkcgo_go_hashSum_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashSum(SB)
GLOBL   ·_mkcgo_go_hashSum_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashSum_trampoline_addr(SB)/8, $_mkcgo_go_hashSum_trampoline<>(SB)

TEXT _mkcgo_go_hashWrite_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_hashWrite(SB)
GLOBL   ·_mkcgo_go_hashWrite_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_hashWrite_trampoline_addr(SB)/8, $_mkcgo_go_hashWrite_trampoline<>(SB)

TEXT _mkcgo_go_initHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_initHMAC(SB)
GLOBL   ·_mkcgo_go_initHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_initHMAC_trampoline_addr(SB)/8, $_mkcgo_go_initHMAC_trampoline<>(SB)

TEXT _mkcgo_go_newPrivateKeyEd25519FromSeed_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_newPrivateKeyEd25519FromSeed(SB)
GLOBL   ·_mkcgo_go_newPrivateKeyEd25519FromSeed_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_newPrivateKeyEd25519FromSeed_trampoline_addr(SB)/8, $_mkcgo_go_newPrivateKeyEd25519FromSeed_trampoline<>(SB)

TEXT _mkcgo_go_newPublicKeyEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_newPublicKeyEd25519(SB)
GLOBL   ·_mkcgo_go_newPublicKeyEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_newPublicKeyEd25519_trampoline_addr(SB)/8, $_mkcgo_go_newPublicKeyEd25519_trampoline<>(SB)

TEXT _mkcgo_go_signEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_signEd25519(SB)
GLOBL   ·_mkcgo_go_signEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_signEd25519_trampoline_addr(SB)/8, $_mkcgo_go_signEd25519_trampoline<>(SB)

TEXT _mkcgo_go_updateHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_updateHMAC(SB)
GLOBL   ·_mkcgo_go_updateHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_updateHMAC_trampoline_addr(SB)/8, $_mkcgo_go_updateHMAC_trampoline<>(SB)

TEXT _mkcgo_go_verifyEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_go_verifyEd25519(SB)
GLOBL   ·_mkcgo_go_verifyEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_go_verifyEd25519_trampoline_addr(SB)/8, $_mkcgo_go_verifyEd25519_trampoline<>(SB)

