// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo

#include "textflag.h"
 
TEXT _mkcgo_MD5_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_MD5(SB)
GLOBL   ·_mkcgo_MD5_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_MD5_trampoline_addr(SB)/8, $_mkcgo_MD5_trampoline<>(SB)

TEXT _mkcgo_SHA1_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_SHA1(SB)
GLOBL   ·_mkcgo_SHA1_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_SHA1_trampoline_addr(SB)/8, $_mkcgo_SHA1_trampoline<>(SB)

TEXT _mkcgo_SHA256_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_SHA256(SB)
GLOBL   ·_mkcgo_SHA256_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_SHA256_trampoline_addr(SB)/8, $_mkcgo_SHA256_trampoline<>(SB)

TEXT _mkcgo_SHA384_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_SHA384(SB)
GLOBL   ·_mkcgo_SHA384_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_SHA384_trampoline_addr(SB)/8, $_mkcgo_SHA384_trampoline<>(SB)

TEXT _mkcgo_SHA512_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_SHA512(SB)
GLOBL   ·_mkcgo_SHA512_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_SHA512_trampoline_addr(SB)/8, $_mkcgo_SHA512_trampoline<>(SB)

TEXT _mkcgo_copyHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_copyHMAC(SB)
GLOBL   ·_mkcgo_copyHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_copyHMAC_trampoline_addr(SB)/8, $_mkcgo_copyHMAC_trampoline<>(SB)

TEXT _mkcgo_decryptAESGCM_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_decryptAESGCM(SB)
GLOBL   ·_mkcgo_decryptAESGCM_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_decryptAESGCM_trampoline_addr(SB)/8, $_mkcgo_decryptAESGCM_trampoline<>(SB)

TEXT _mkcgo_encryptAESGCM_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_encryptAESGCM(SB)
GLOBL   ·_mkcgo_encryptAESGCM_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_encryptAESGCM_trampoline_addr(SB)/8, $_mkcgo_encryptAESGCM_trampoline<>(SB)

TEXT _mkcgo_expandHKDF_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_expandHKDF(SB)
GLOBL   ·_mkcgo_expandHKDF_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_expandHKDF_trampoline_addr(SB)/8, $_mkcgo_expandHKDF_trampoline<>(SB)

TEXT _mkcgo_extractHKDF_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_extractHKDF(SB)
GLOBL   ·_mkcgo_extractHKDF_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_extractHKDF_trampoline_addr(SB)/8, $_mkcgo_extractHKDF_trampoline<>(SB)

TEXT _mkcgo_finalizeHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_finalizeHMAC(SB)
GLOBL   ·_mkcgo_finalizeHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_finalizeHMAC_trampoline_addr(SB)/8, $_mkcgo_finalizeHMAC_trampoline<>(SB)

TEXT _mkcgo_freeHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_freeHMAC(SB)
GLOBL   ·_mkcgo_freeHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_freeHMAC_trampoline_addr(SB)/8, $_mkcgo_freeHMAC_trampoline<>(SB)

TEXT _mkcgo_generateKeyEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_generateKeyEd25519(SB)
GLOBL   ·_mkcgo_generateKeyEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_generateKeyEd25519_trampoline_addr(SB)/8, $_mkcgo_generateKeyEd25519_trampoline<>(SB)

TEXT _mkcgo_hashBlockSize_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashBlockSize(SB)
GLOBL   ·_mkcgo_hashBlockSize_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashBlockSize_trampoline_addr(SB)/8, $_mkcgo_hashBlockSize_trampoline<>(SB)

TEXT _mkcgo_hashCopy_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashCopy(SB)
GLOBL   ·_mkcgo_hashCopy_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashCopy_trampoline_addr(SB)/8, $_mkcgo_hashCopy_trampoline<>(SB)

TEXT _mkcgo_hashFree_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashFree(SB)
GLOBL   ·_mkcgo_hashFree_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashFree_trampoline_addr(SB)/8, $_mkcgo_hashFree_trampoline<>(SB)

TEXT _mkcgo_hashNew_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashNew(SB)
GLOBL   ·_mkcgo_hashNew_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashNew_trampoline_addr(SB)/8, $_mkcgo_hashNew_trampoline<>(SB)

TEXT _mkcgo_hashReset_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashReset(SB)
GLOBL   ·_mkcgo_hashReset_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashReset_trampoline_addr(SB)/8, $_mkcgo_hashReset_trampoline<>(SB)

TEXT _mkcgo_hashSize_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashSize(SB)
GLOBL   ·_mkcgo_hashSize_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashSize_trampoline_addr(SB)/8, $_mkcgo_hashSize_trampoline<>(SB)

TEXT _mkcgo_hashSum_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashSum(SB)
GLOBL   ·_mkcgo_hashSum_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashSum_trampoline_addr(SB)/8, $_mkcgo_hashSum_trampoline<>(SB)

TEXT _mkcgo_hashWrite_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_hashWrite(SB)
GLOBL   ·_mkcgo_hashWrite_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_hashWrite_trampoline_addr(SB)/8, $_mkcgo_hashWrite_trampoline<>(SB)

TEXT _mkcgo_initHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_initHMAC(SB)
GLOBL   ·_mkcgo_initHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_initHMAC_trampoline_addr(SB)/8, $_mkcgo_initHMAC_trampoline<>(SB)

TEXT _mkcgo_newPrivateKeyEd25519FromSeed_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_newPrivateKeyEd25519FromSeed(SB)
GLOBL   ·_mkcgo_newPrivateKeyEd25519FromSeed_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_newPrivateKeyEd25519FromSeed_trampoline_addr(SB)/8, $_mkcgo_newPrivateKeyEd25519FromSeed_trampoline<>(SB)

TEXT _mkcgo_newPublicKeyEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_newPublicKeyEd25519(SB)
GLOBL   ·_mkcgo_newPublicKeyEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_newPublicKeyEd25519_trampoline_addr(SB)/8, $_mkcgo_newPublicKeyEd25519_trampoline<>(SB)

TEXT _mkcgo_signEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_signEd25519(SB)
GLOBL   ·_mkcgo_signEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_signEd25519_trampoline_addr(SB)/8, $_mkcgo_signEd25519_trampoline<>(SB)

TEXT _mkcgo_updateHMAC_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_updateHMAC(SB)
GLOBL   ·_mkcgo_updateHMAC_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_updateHMAC_trampoline_addr(SB)/8, $_mkcgo_updateHMAC_trampoline<>(SB)

TEXT _mkcgo_verifyEd25519_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_verifyEd25519(SB)
GLOBL   ·_mkcgo_verifyEd25519_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_verifyEd25519_trampoline_addr(SB)/8, $_mkcgo_verifyEd25519_trampoline<>(SB)

