# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: "Setup gotip"
description: "Setup gotip"

inputs:
  macos-version:
    description: "macOS version"
    required: true
    default: "macos-15"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: 1.25.x

    - name: Bulild gotip
      shell: bash
      if: steps.gotip.outputs.cache-hit != 'true'
      run: |
        go install golang.org/dl/gotip@latest
        printf 'y\n' | gotip download

    - name: Add gotip to the PATH
      shell: bash
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
