# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: "Setup gotip"
description: "Setup gotip"

inputs:
  macos-version:
    description: "macOS version"
    required: true
    default: "macos-15"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: 1.25.x

    - name: Cache gotip
      id: gotip
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          $HOME/go/bin
          $HOME/.cache/gotip
          $HOME/.gotip
        key: gotip-${{ inputs.macos-version }}-703335
        restore-keys: |
          gotip-${{ inputs.macos-version }}-

    - name: Download CL containing patches required for CGO-less
      shell: bash
      if: steps.gotip.outputs.cache-hit != 'true'
      run: |
        go install golang.org/dl/gotip@latest
        yes y | gotip download 703335

    - name: Add gotip to the PATH
      shell: bash
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
