// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo && darwin

package security

import (
	"syscall"
	"unsafe"
)

//go:linkname syscall_syscall syscall.syscall
//go:linkname syscall_syscall6 syscall.syscall6
//go:linkname syscall_syscall9 syscall.syscall9

func syscall_syscall(fn, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno)
func syscall_syscall6(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno)
func syscall_syscall9(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, err syscall.Errno)

//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecRandomDefault_ptr kSecRandomDefault "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kCFAllocatorDefault_ptr kCFAllocatorDefault "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeyTypeECSECPrimeRandom_ptr kSecAttrKeyTypeECSECPrimeRandom "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeyTypeRSA_ptr kSecAttrKeyTypeRSA "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeyClassPublic_ptr kSecAttrKeyClassPublic "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeyClassPrivate_ptr kSecAttrKeyClassPrivate "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeyType_ptr kSecAttrKeyType "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeySizeInBits_ptr kSecAttrKeySizeInBits "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecAttrKeyClass_ptr kSecAttrKeyClass "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard_ptr kSecKeyAlgorithmECDHKeyExchangeStandard "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1_ptr kSecKeyAlgorithmRSASignatureDigestPSSSHA1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224_ptr kSecKeyAlgorithmRSASignatureDigestPSSSHA224 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256_ptr kSecKeyAlgorithmRSASignatureDigestPSSSHA256 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384_ptr kSecKeyAlgorithmRSASignatureDigestPSSSHA384 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512_ptr kSecKeyAlgorithmRSASignatureDigestPSSSHA512 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionRaw_ptr kSecKeyAlgorithmRSAEncryptionRaw "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1_ptr kSecKeyAlgorithmRSAEncryptionPKCS1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1_ptr kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224_ptr kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256_ptr kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384_ptr kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512_ptr kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw_ptr kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1_ptr kSecKeyAlgorithmRSAEncryptionOAEPSHA1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224_ptr kSecKeyAlgorithmRSAEncryptionOAEPSHA224 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256_ptr kSecKeyAlgorithmRSAEncryptionOAEPSHA256 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384_ptr kSecKeyAlgorithmRSAEncryptionOAEPSHA384 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512_ptr kSecKeyAlgorithmRSAEncryptionOAEPSHA512 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic github.com/microsoft/go-crypto-darwin/internal/security._mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962_ptr kSecKeyAlgorithmECDSASignatureDigestX962 "/System/Library/Frameworks/Security.framework/Versions/A/Security"

//go:cgo_import_dynamic _mkcgo_CFDataCreate CFDataCreate "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDataGetBytePtr CFDataGetBytePtr "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDataGetLength CFDataGetLength "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDictionaryCreate CFDictionaryCreate "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDictionaryCreateMutable CFDictionaryCreateMutable "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDictionarySetValue CFDictionarySetValue "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFErrorCopyDescription CFErrorCopyDescription "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFErrorGetCode CFErrorGetCode "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFNumberCreate CFNumberCreate "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFRelease CFRelease "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFStringGetCStringPtr CFStringGetCStringPtr "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFStringGetLength CFStringGetLength "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_SecKeyCopyExternalRepresentation SecKeyCopyExternalRepresentation "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCopyKeyExchangeResult SecKeyCopyKeyExchangeResult "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCopyPublicKey SecKeyCopyPublicKey "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateDecryptedData SecKeyCreateDecryptedData "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateEncryptedData SecKeyCreateEncryptedData "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateRandomKey SecKeyCreateRandomKey "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateSignature SecKeyCreateSignature "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateWithData SecKeyCreateWithData "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyGetBlockSize SecKeyGetBlockSize "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyIsAlgorithmSupported SecKeyIsAlgorithmSupported "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyVerifySignature SecKeyVerifySignature "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecRandomCopyBytes SecRandomCopyBytes "/System/Library/Frameworks/Security.framework/Versions/A/Security"

type Boolean unsafe.Pointer
type SecRandomRef unsafe.Pointer
type SecKeyRef unsafe.Pointer
type CFDataRef unsafe.Pointer
type CFTypeRef unsafe.Pointer
type CFStringRef unsafe.Pointer
type CFDictionaryRef unsafe.Pointer
type CFMutableDictionaryRef unsafe.Pointer
type CFNumberRef unsafe.Pointer
type CFErrorRef unsafe.Pointer
type CFAllocatorRef unsafe.Pointer
type CFDictionaryKeyCallBacks unsafe.Pointer
type CFDictionaryValueCallBacks unsafe.Pointer
type CFIndex = int32
type SecKeyAlgorithm = CFStringRef

type SecKeyOperationType int32

const (
	KSecKeyOperationTypeSign        SecKeyOperationType = 0
	KSecKeyOperationTypeVerify      SecKeyOperationType = 1
	KSecKeyOperationTypeEncrypt     SecKeyOperationType = 2
	KSecKeyOperationTypeDecrypt     SecKeyOperationType = 3
	KSecKeyOperationTypeKeyExchange SecKeyOperationType = 4
)

type CFStringEncoding int32

const (
	KCFStringEncodingUTF8 CFStringEncoding = 0x08000100
)

type CFNumberType int32

const (
	KCFNumberIntType CFNumberType = 9
)

var (
	_mkcgo_kSecRandomDefault_ptr                                *SecRandomRef
	_mkcgo_kCFAllocatorDefault_ptr                              *CFAllocatorRef
	_mkcgo_kSecAttrKeyTypeECSECPrimeRandom_ptr                  *CFStringRef
	_mkcgo_kSecAttrKeyTypeRSA_ptr                               *CFStringRef
	_mkcgo_kSecAttrKeyClassPublic_ptr                           *CFStringRef
	_mkcgo_kSecAttrKeyClassPrivate_ptr                          *CFStringRef
	_mkcgo_kSecAttrKeyType_ptr                                  *CFStringRef
	_mkcgo_kSecAttrKeySizeInBits_ptr                            *CFStringRef
	_mkcgo_kSecAttrKeyClass_ptr                                 *CFStringRef
	_mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard_ptr          *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1_ptr        *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224_ptr      *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256_ptr      *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384_ptr      *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512_ptr      *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionRaw_ptr                 *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1_ptr               *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1_ptr   *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224_ptr *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256_ptr *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384_ptr *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512_ptr *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw_ptr    *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1_ptr            *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224_ptr          *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256_ptr          *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384_ptr          *CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512_ptr          *CFStringRef
	_mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962_ptr         *CFStringRef
)

var (
	KSecRandomDefault                                SecRandomRef   = nil
	KCFAllocatorDefault                              CFAllocatorRef = nil
	KSecAttrKeyTypeECSECPrimeRandom                  CFStringRef    = *_mkcgo_kSecAttrKeyTypeECSECPrimeRandom_ptr
	KSecAttrKeyTypeRSA                               CFStringRef    = *_mkcgo_kSecAttrKeyTypeRSA_ptr
	KSecAttrKeyClassPublic                           CFStringRef    = *_mkcgo_kSecAttrKeyClassPublic_ptr
	KSecAttrKeyClassPrivate                          CFStringRef    = *_mkcgo_kSecAttrKeyClassPrivate_ptr
	KSecAttrKeyType                                  CFStringRef    = *_mkcgo_kSecAttrKeyType_ptr
	KSecAttrKeySizeInBits                            CFStringRef    = *_mkcgo_kSecAttrKeySizeInBits_ptr
	KSecAttrKeyClass                                 CFStringRef    = *_mkcgo_kSecAttrKeyClass_ptr
	KSecKeyAlgorithmECDHKeyExchangeStandard          CFStringRef    = *_mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard_ptr
	KSecKeyAlgorithmRSASignatureDigestPSSSHA1        CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1_ptr
	KSecKeyAlgorithmRSASignatureDigestPSSSHA224      CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224_ptr
	KSecKeyAlgorithmRSASignatureDigestPSSSHA256      CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256_ptr
	KSecKeyAlgorithmRSASignatureDigestPSSSHA384      CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384_ptr
	KSecKeyAlgorithmRSASignatureDigestPSSSHA512      CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512_ptr
	KSecKeyAlgorithmRSAEncryptionRaw                 CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionRaw_ptr
	KSecKeyAlgorithmRSAEncryptionPKCS1               CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1_ptr
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1   CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1_ptr
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224_ptr
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256_ptr
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384_ptr
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512_ptr
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw    CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw_ptr
	KSecKeyAlgorithmRSAEncryptionOAEPSHA1            CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1_ptr
	KSecKeyAlgorithmRSAEncryptionOAEPSHA224          CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224_ptr
	KSecKeyAlgorithmRSAEncryptionOAEPSHA256          CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256_ptr
	KSecKeyAlgorithmRSAEncryptionOAEPSHA384          CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384_ptr
	KSecKeyAlgorithmRSAEncryptionOAEPSHA512          CFStringRef    = *_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512_ptr
	KSecKeyAlgorithmECDSASignatureDigestX962         CFStringRef    = *_mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962_ptr
)

var _mkcgo_CFDataCreate_trampoline_addr uintptr

func CFDataCreate(allocator CFAllocatorRef, bytes *uint8, length CFIndex) CFDataRef {
	r0, _, _ := syscall_syscall(_mkcgo_CFDataCreate_trampoline_addr, uintptr(allocator), uintptr(unsafe.Pointer(bytes)), uintptr(length))
	return CFDataRef(r0)
}

var _mkcgo_CFDataGetBytePtr_trampoline_addr uintptr

func CFDataGetBytePtr(data CFDataRef) *uint8 {
	r0, _, _ := syscall_syscall(_mkcgo_CFDataGetBytePtr_trampoline_addr, uintptr(data), 0, 0)
	return (*uint8)(unsafe.Pointer(r0))
}

var _mkcgo_CFDataGetLength_trampoline_addr uintptr

func CFDataGetLength(data CFDataRef) CFIndex {
	r0, _, _ := syscall_syscall(_mkcgo_CFDataGetLength_trampoline_addr, uintptr(data), 0, 0)
	return CFIndex(r0)
}

var _mkcgo_CFDictionaryCreate_trampoline_addr uintptr

func CFDictionaryCreate(allocator CFAllocatorRef, keys *unsafe.Pointer, values *unsafe.Pointer, numValues CFIndex, keyCallBacks *CFDictionaryKeyCallBacks, valueCallBacks *CFDictionaryValueCallBacks) CFDictionaryRef {
	r0, _, _ := syscall_syscall6(_mkcgo_CFDictionaryCreate_trampoline_addr, uintptr(allocator), uintptr(unsafe.Pointer(keys)), uintptr(unsafe.Pointer(values)), uintptr(numValues), uintptr(unsafe.Pointer(keyCallBacks)), uintptr(unsafe.Pointer(valueCallBacks)))
	return CFDictionaryRef(r0)
}

var _mkcgo_CFDictionaryCreateMutable_trampoline_addr uintptr

func CFDictionaryCreateMutable(allocator CFAllocatorRef, capacity CFIndex, keyCallBacks *CFDictionaryKeyCallBacks, valueCallBacks *CFDictionaryValueCallBacks) CFMutableDictionaryRef {
	r0, _, _ := syscall_syscall6(_mkcgo_CFDictionaryCreateMutable_trampoline_addr, uintptr(allocator), uintptr(capacity), uintptr(unsafe.Pointer(keyCallBacks)), uintptr(unsafe.Pointer(valueCallBacks)), 0, 0)
	return CFMutableDictionaryRef(r0)
}

var _mkcgo_CFDictionarySetValue_trampoline_addr uintptr

func CFDictionarySetValue(theDict CFMutableDictionaryRef, key unsafe.Pointer, value unsafe.Pointer) {
	syscall_syscall(_mkcgo_CFDictionarySetValue_trampoline_addr, uintptr(theDict), uintptr(key), uintptr(value))
}

var _mkcgo_CFErrorCopyDescription_trampoline_addr uintptr

func CFErrorCopyDescription(error CFErrorRef) CFStringRef {
	r0, _, _ := syscall_syscall(_mkcgo_CFErrorCopyDescription_trampoline_addr, uintptr(error), 0, 0)
	return CFStringRef(r0)
}

var _mkcgo_CFErrorGetCode_trampoline_addr uintptr

func CFErrorGetCode(error CFErrorRef) CFIndex {
	r0, _, _ := syscall_syscall(_mkcgo_CFErrorGetCode_trampoline_addr, uintptr(error), 0, 0)
	return CFIndex(r0)
}

var _mkcgo_CFNumberCreate_trampoline_addr uintptr

func CFNumberCreate(allocator CFAllocatorRef, theType CFNumberType, valuePtr unsafe.Pointer) CFNumberRef {
	r0, _, _ := syscall_syscall(_mkcgo_CFNumberCreate_trampoline_addr, uintptr(allocator), uintptr(theType), uintptr(valuePtr))
	return CFNumberRef(r0)
}

var _mkcgo_CFRelease_trampoline_addr uintptr

func CFRelease(cf CFTypeRef) {
	syscall_syscall(_mkcgo_CFRelease_trampoline_addr, uintptr(cf), 0, 0)
}

var _mkcgo_CFStringGetCStringPtr_trampoline_addr uintptr

func CFStringGetCStringPtr(str CFStringRef, encoding CFStringEncoding) *byte {
	r0, _, _ := syscall_syscall(_mkcgo_CFStringGetCStringPtr_trampoline_addr, uintptr(str), uintptr(encoding), 0)
	return (*byte)(unsafe.Pointer(r0))
}

var _mkcgo_CFStringGetLength_trampoline_addr uintptr

func CFStringGetLength(str CFStringRef) CFIndex {
	r0, _, _ := syscall_syscall(_mkcgo_CFStringGetLength_trampoline_addr, uintptr(str), 0, 0)
	return CFIndex(r0)
}

var _mkcgo_SecKeyCopyExternalRepresentation_trampoline_addr uintptr

func SecKeyCopyExternalRepresentation(key SecKeyRef, error *CFErrorRef) CFDataRef {
	r0, _, _ := syscall_syscall(_mkcgo_SecKeyCopyExternalRepresentation_trampoline_addr, uintptr(key), uintptr(unsafe.Pointer(error)), 0)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCopyKeyExchangeResult_trampoline_addr uintptr

func SecKeyCopyKeyExchangeResult(privateKey SecKeyRef, algorithm SecKeyAlgorithm, publicKey SecKeyRef, parameters CFDictionaryRef, error *CFErrorRef) CFDataRef {
	r0, _, _ := syscall_syscall6(_mkcgo_SecKeyCopyKeyExchangeResult_trampoline_addr, uintptr(privateKey), uintptr(algorithm), uintptr(publicKey), uintptr(parameters), uintptr(unsafe.Pointer(error)), 0)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCopyPublicKey_trampoline_addr uintptr

func SecKeyCopyPublicKey(key SecKeyRef) SecKeyRef {
	r0, _, _ := syscall_syscall(_mkcgo_SecKeyCopyPublicKey_trampoline_addr, uintptr(key), 0, 0)
	return SecKeyRef(r0)
}

var _mkcgo_SecKeyCreateDecryptedData_trampoline_addr uintptr

func SecKeyCreateDecryptedData(key SecKeyRef, algorithm SecKeyAlgorithm, ciphertext CFDataRef, error *CFErrorRef) CFDataRef {
	r0, _, _ := syscall_syscall6(_mkcgo_SecKeyCreateDecryptedData_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(ciphertext), uintptr(unsafe.Pointer(error)), 0, 0)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCreateEncryptedData_trampoline_addr uintptr

func SecKeyCreateEncryptedData(key SecKeyRef, algorithm SecKeyAlgorithm, plaintext CFDataRef, error *CFErrorRef) CFDataRef {
	r0, _, _ := syscall_syscall6(_mkcgo_SecKeyCreateEncryptedData_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(plaintext), uintptr(unsafe.Pointer(error)), 0, 0)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCreateRandomKey_trampoline_addr uintptr

func SecKeyCreateRandomKey(parameters CFDictionaryRef, error *CFErrorRef) SecKeyRef {
	r0, _, _ := syscall_syscall(_mkcgo_SecKeyCreateRandomKey_trampoline_addr, uintptr(parameters), uintptr(unsafe.Pointer(error)), 0)
	return SecKeyRef(r0)
}

var _mkcgo_SecKeyCreateSignature_trampoline_addr uintptr

func SecKeyCreateSignature(key SecKeyRef, algorithm SecKeyAlgorithm, data CFDataRef, error *CFErrorRef) CFDataRef {
	r0, _, _ := syscall_syscall6(_mkcgo_SecKeyCreateSignature_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(data), uintptr(unsafe.Pointer(error)), 0, 0)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCreateWithData_trampoline_addr uintptr

func SecKeyCreateWithData(keyData CFDataRef, attributes CFDictionaryRef, error *CFErrorRef) SecKeyRef {
	r0, _, _ := syscall_syscall(_mkcgo_SecKeyCreateWithData_trampoline_addr, uintptr(keyData), uintptr(attributes), uintptr(unsafe.Pointer(error)))
	return SecKeyRef(r0)
}

var _mkcgo_SecKeyGetBlockSize_trampoline_addr uintptr

func SecKeyGetBlockSize(key SecKeyRef) int {
	r0, _, _ := syscall_syscall(_mkcgo_SecKeyGetBlockSize_trampoline_addr, uintptr(key), 0, 0)
	return int(r0)
}

var _mkcgo_SecKeyIsAlgorithmSupported_trampoline_addr uintptr

func SecKeyIsAlgorithmSupported(key SecKeyRef, operation SecKeyOperationType, algorithm SecKeyAlgorithm) int32 {
	r0, _, _ := syscall_syscall(_mkcgo_SecKeyIsAlgorithmSupported_trampoline_addr, uintptr(key), uintptr(operation), uintptr(algorithm))
	return int32(r0)
}

var _mkcgo_SecKeyVerifySignature_trampoline_addr uintptr

func SecKeyVerifySignature(key SecKeyRef, algorithm SecKeyAlgorithm, signedData CFDataRef, signature CFDataRef, error *CFErrorRef) int32 {
	r0, _, _ := syscall_syscall6(_mkcgo_SecKeyVerifySignature_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(signedData), uintptr(signature), uintptr(unsafe.Pointer(error)), 0)
	return int32(r0)
}

var _mkcgo_SecRandomCopyBytes_trampoline_addr uintptr

func SecRandomCopyBytes(rnd SecRandomRef, count int, bytes unsafe.Pointer) int32 {
	r0, _, _ := syscall_syscall(_mkcgo_SecRandomCopyBytes_trampoline_addr, uintptr(rnd), uintptr(count), uintptr(bytes))
	return int32(r0)
}
