// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

package security

const (
	KSecKeyOperationTypeSign        SecKeyOperationType = 0
	KSecKeyOperationTypeVerify      SecKeyOperationType = 1
	KSecKeyOperationTypeEncrypt     SecKeyOperationType = 2
	KSecKeyOperationTypeDecrypt     SecKeyOperationType = 3
	KSecKeyOperationTypeKeyExchange SecKeyOperationType = 4
)

const (
	KCFStringEncodingUTF8 CFStringEncoding = 0x08000100
)

const (
	KCFNumberIntType CFNumberType = 9
)
