// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

//go:build go1.24 && !cmd_go_bootstrap

package security

/*
#cgo noescape _mkcgo_CFDataCreate
#cgo nocallback _mkcgo_CFDataCreate
#cgo noescape _mkcgo_SecKeyCopyExternalRepresentation
#cgo nocallback _mkcgo_SecKeyCopyExternalRepresentation
#cgo noescape _mkcgo_SecKeyCreateRandomKey
#cgo nocallback _mkcgo_SecKeyCreateRandomKey
#cgo noescape _mkcgo_SecRandomCopyBytes
#cgo nocallback _mkcgo_SecRandomCopyBytes
*/
import "C"
