// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo

package security

import (
	"runtime"
	"unsafe"
)

//go:cgo_import_dynamic _mkcgo_kCFAllocatorDefault kCFAllocatorDefault "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:linkname _mkcgo_kCFAllocatorDefault _mkcgo_kCFAllocatorDefault
//go:cgo_import_dynamic _mkcgo_kSecRandomDefault kSecRandomDefault "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecRandomDefault _mkcgo_kSecRandomDefault
//go:cgo_import_dynamic _mkcgo_kSecAttrKeyTypeECSECPrimeRandom kSecAttrKeyTypeECSECPrimeRandom "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeyTypeECSECPrimeRandom _mkcgo_kSecAttrKeyTypeECSECPrimeRandom
//go:cgo_import_dynamic _mkcgo_kSecAttrKeyTypeRSA kSecAttrKeyTypeRSA "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeyTypeRSA _mkcgo_kSecAttrKeyTypeRSA
//go:cgo_import_dynamic _mkcgo_kSecAttrKeyClassPublic kSecAttrKeyClassPublic "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeyClassPublic _mkcgo_kSecAttrKeyClassPublic
//go:cgo_import_dynamic _mkcgo_kSecAttrKeyClassPrivate kSecAttrKeyClassPrivate "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeyClassPrivate _mkcgo_kSecAttrKeyClassPrivate
//go:cgo_import_dynamic _mkcgo_kSecAttrKeyType kSecAttrKeyType "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeyType _mkcgo_kSecAttrKeyType
//go:cgo_import_dynamic _mkcgo_kSecAttrKeySizeInBits kSecAttrKeySizeInBits "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeySizeInBits _mkcgo_kSecAttrKeySizeInBits
//go:cgo_import_dynamic _mkcgo_kSecAttrKeyClass kSecAttrKeyClass "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecAttrKeyClass _mkcgo_kSecAttrKeyClass
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard kSecKeyAlgorithmECDHKeyExchangeStandard "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard _mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1 kSecKeyAlgorithmRSASignatureDigestPSSSHA1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224 kSecKeyAlgorithmRSASignatureDigestPSSSHA224 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256 kSecKeyAlgorithmRSASignatureDigestPSSSHA256 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384 kSecKeyAlgorithmRSASignatureDigestPSSSHA384 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512 kSecKeyAlgorithmRSASignatureDigestPSSSHA512 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionRaw kSecKeyAlgorithmRSAEncryptionRaw "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionRaw _mkcgo_kSecKeyAlgorithmRSAEncryptionRaw
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1 kSecKeyAlgorithmRSAEncryptionPKCS1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1 _mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1 kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw _mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1 kSecKeyAlgorithmRSAEncryptionOAEPSHA1 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1 _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224 kSecKeyAlgorithmRSAEncryptionOAEPSHA224 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224 _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256 kSecKeyAlgorithmRSAEncryptionOAEPSHA256 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256 _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384 kSecKeyAlgorithmRSAEncryptionOAEPSHA384 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384 _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512 kSecKeyAlgorithmRSAEncryptionOAEPSHA512 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512 _mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512
//go:cgo_import_dynamic _mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962 kSecKeyAlgorithmECDSASignatureDigestX962 "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:linkname _mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962 _mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962

//go:cgo_import_dynamic _mkcgo_CFDataCreate CFDataCreate "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDataGetBytePtr CFDataGetBytePtr "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDataGetLength CFDataGetLength "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDictionaryCreate CFDictionaryCreate "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDictionaryCreateMutable CFDictionaryCreateMutable "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFDictionarySetValue CFDictionarySetValue "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFErrorCopyDescription CFErrorCopyDescription "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFErrorGetCode CFErrorGetCode "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFNumberCreate CFNumberCreate "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFRelease CFRelease "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFStringGetCStringPtr CFStringGetCStringPtr "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_CFStringGetLength CFStringGetLength "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//go:cgo_import_dynamic _mkcgo_SecKeyCopyExternalRepresentation SecKeyCopyExternalRepresentation "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCopyKeyExchangeResult SecKeyCopyKeyExchangeResult "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCopyPublicKey SecKeyCopyPublicKey "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateDecryptedData SecKeyCreateDecryptedData "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateEncryptedData SecKeyCreateEncryptedData "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateRandomKey SecKeyCreateRandomKey "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateSignature SecKeyCreateSignature "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyCreateWithData SecKeyCreateWithData "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyGetBlockSize SecKeyGetBlockSize "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyIsAlgorithmSupported SecKeyIsAlgorithmSupported "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecKeyVerifySignature SecKeyVerifySignature "/System/Library/Frameworks/Security.framework/Versions/A/Security"
//go:cgo_import_dynamic _mkcgo_SecRandomCopyBytes SecRandomCopyBytes "/System/Library/Frameworks/Security.framework/Versions/A/Security"

type Boolean = byte
type SecRandomRef unsafe.Pointer
type SecKeyRef unsafe.Pointer
type CFDataRef unsafe.Pointer
type CFTypeRef unsafe.Pointer
type CFStringRef unsafe.Pointer
type CFDictionaryRef unsafe.Pointer
type CFMutableDictionaryRef unsafe.Pointer
type CFNumberRef unsafe.Pointer
type CFErrorRef unsafe.Pointer
type CFAllocatorRef unsafe.Pointer
type CFDictionaryKeyCallBacks unsafe.Pointer
type CFDictionaryValueCallBacks unsafe.Pointer
type CFIndex = int32
type SecKeyAlgorithm = CFStringRef

type SecKeyOperationType int32

type CFStringEncoding int32

type CFNumberType int32

var (
	_mkcgo_kCFAllocatorDefault                              CFAllocatorRef
	_mkcgo_kSecRandomDefault                                SecRandomRef
	_mkcgo_kSecAttrKeyTypeECSECPrimeRandom                  CFStringRef
	_mkcgo_kSecAttrKeyTypeRSA                               CFStringRef
	_mkcgo_kSecAttrKeyClassPublic                           CFStringRef
	_mkcgo_kSecAttrKeyClassPrivate                          CFStringRef
	_mkcgo_kSecAttrKeyType                                  CFStringRef
	_mkcgo_kSecAttrKeySizeInBits                            CFStringRef
	_mkcgo_kSecAttrKeyClass                                 CFStringRef
	_mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard          CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1        CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224      CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256      CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384      CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512      CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionRaw                 CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1               CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1   CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 CFStringRef
	_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw    CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1            CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224          CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256          CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384          CFStringRef
	_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512          CFStringRef
	_mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962         CFStringRef
)

//go:noinline
func _mkcgo_addr_kCFAllocatorDefault() *CFAllocatorRef { return &_mkcgo_kCFAllocatorDefault }

//go:noinline
func _mkcgo_addr_kSecRandomDefault() *SecRandomRef { return &_mkcgo_kSecRandomDefault }

//go:noinline
func _mkcgo_addr_kSecAttrKeyTypeECSECPrimeRandom() *CFStringRef {
	return &_mkcgo_kSecAttrKeyTypeECSECPrimeRandom
}

//go:noinline
func _mkcgo_addr_kSecAttrKeyTypeRSA() *CFStringRef { return &_mkcgo_kSecAttrKeyTypeRSA }

//go:noinline
func _mkcgo_addr_kSecAttrKeyClassPublic() *CFStringRef { return &_mkcgo_kSecAttrKeyClassPublic }

//go:noinline
func _mkcgo_addr_kSecAttrKeyClassPrivate() *CFStringRef { return &_mkcgo_kSecAttrKeyClassPrivate }

//go:noinline
func _mkcgo_addr_kSecAttrKeyType() *CFStringRef { return &_mkcgo_kSecAttrKeyType }

//go:noinline
func _mkcgo_addr_kSecAttrKeySizeInBits() *CFStringRef { return &_mkcgo_kSecAttrKeySizeInBits }

//go:noinline
func _mkcgo_addr_kSecAttrKeyClass() *CFStringRef { return &_mkcgo_kSecAttrKeyClass }

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmECDHKeyExchangeStandard() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmECDHKeyExchangeStandard
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA1() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA1
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA224() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA224
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA256() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA256
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA384() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA384
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA512() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPSSSHA512
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionRaw() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionRaw
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionPKCS1() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionPKCS1
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA1() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA1
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA224() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA224
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA256() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA256
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA384() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA384
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA512() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmRSAEncryptionOAEPSHA512
}

//go:noinline
func _mkcgo_addr_kSecKeyAlgorithmECDSASignatureDigestX962() *CFStringRef {
	return &_mkcgo_kSecKeyAlgorithmECDSASignatureDigestX962
}

var (
	KCFAllocatorDefault                              CFAllocatorRef = *_mkcgo_addr_kCFAllocatorDefault()
	KSecRandomDefault                                SecRandomRef   = *_mkcgo_addr_kSecRandomDefault()
	KSecAttrKeyTypeECSECPrimeRandom                  CFStringRef    = *_mkcgo_addr_kSecAttrKeyTypeECSECPrimeRandom()
	KSecAttrKeyTypeRSA                               CFStringRef    = *_mkcgo_addr_kSecAttrKeyTypeRSA()
	KSecAttrKeyClassPublic                           CFStringRef    = *_mkcgo_addr_kSecAttrKeyClassPublic()
	KSecAttrKeyClassPrivate                          CFStringRef    = *_mkcgo_addr_kSecAttrKeyClassPrivate()
	KSecAttrKeyType                                  CFStringRef    = *_mkcgo_addr_kSecAttrKeyType()
	KSecAttrKeySizeInBits                            CFStringRef    = *_mkcgo_addr_kSecAttrKeySizeInBits()
	KSecAttrKeyClass                                 CFStringRef    = *_mkcgo_addr_kSecAttrKeyClass()
	KSecKeyAlgorithmECDHKeyExchangeStandard          CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmECDHKeyExchangeStandard()
	KSecKeyAlgorithmRSASignatureDigestPSSSHA1        CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA1()
	KSecKeyAlgorithmRSASignatureDigestPSSSHA224      CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA224()
	KSecKeyAlgorithmRSASignatureDigestPSSSHA256      CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA256()
	KSecKeyAlgorithmRSASignatureDigestPSSSHA384      CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA384()
	KSecKeyAlgorithmRSASignatureDigestPSSSHA512      CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPSSSHA512()
	KSecKeyAlgorithmRSAEncryptionRaw                 CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionRaw()
	KSecKeyAlgorithmRSAEncryptionPKCS1               CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionPKCS1()
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1   CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA1()
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224 CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA224()
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256 CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA256()
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384 CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA384()
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512 CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15SHA512()
	KSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw    CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSASignatureDigestPKCS1v15Raw()
	KSecKeyAlgorithmRSAEncryptionOAEPSHA1            CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA1()
	KSecKeyAlgorithmRSAEncryptionOAEPSHA224          CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA224()
	KSecKeyAlgorithmRSAEncryptionOAEPSHA256          CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA256()
	KSecKeyAlgorithmRSAEncryptionOAEPSHA384          CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA384()
	KSecKeyAlgorithmRSAEncryptionOAEPSHA512          CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmRSAEncryptionOAEPSHA512()
	KSecKeyAlgorithmECDSASignatureDigestX962         CFStringRef    = *_mkcgo_addr_kSecKeyAlgorithmECDSASignatureDigestX962()
)

var _mkcgo_CFDataCreate_trampoline_addr uintptr

func CFDataCreate(allocator CFAllocatorRef, bytes *uint8, length CFIndex) CFDataRef {
	r0, _, _ := syscallN(_mkcgo_CFDataCreate_trampoline_addr, uintptr(allocator), uintptr(unsafe.Pointer(bytes)), uintptr(length))
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(bytes)
	return CFDataRef(r0)
}

var _mkcgo_CFDataGetBytePtr_trampoline_addr uintptr

func CFDataGetBytePtr(data CFDataRef) *uint8 {
	r0, _, _ := syscallN(_mkcgo_CFDataGetBytePtr_trampoline_addr, uintptr(data))
	runtime.KeepAlive(data)
	return (*uint8)(unsafe.Pointer(r0))
}

var _mkcgo_CFDataGetLength_trampoline_addr uintptr

func CFDataGetLength(data CFDataRef) CFIndex {
	r0, _, _ := syscallN(_mkcgo_CFDataGetLength_trampoline_addr, uintptr(data))
	runtime.KeepAlive(data)
	return CFIndex(r0)
}

var _mkcgo_CFDictionaryCreate_trampoline_addr uintptr

func CFDictionaryCreate(allocator CFAllocatorRef, keys *unsafe.Pointer, values *unsafe.Pointer, numValues CFIndex, keyCallBacks *CFDictionaryKeyCallBacks, valueCallBacks *CFDictionaryValueCallBacks) CFDictionaryRef {
	r0, _, _ := syscallN(_mkcgo_CFDictionaryCreate_trampoline_addr, uintptr(allocator), uintptr(unsafe.Pointer(keys)), uintptr(unsafe.Pointer(values)), uintptr(numValues), uintptr(unsafe.Pointer(keyCallBacks)), uintptr(unsafe.Pointer(valueCallBacks)))
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(keys)
	runtime.KeepAlive(values)
	runtime.KeepAlive(keyCallBacks)
	runtime.KeepAlive(valueCallBacks)
	return CFDictionaryRef(r0)
}

var _mkcgo_CFDictionaryCreateMutable_trampoline_addr uintptr

func CFDictionaryCreateMutable(allocator CFAllocatorRef, capacity CFIndex, keyCallBacks *CFDictionaryKeyCallBacks, valueCallBacks *CFDictionaryValueCallBacks) CFMutableDictionaryRef {
	r0, _, _ := syscallN(_mkcgo_CFDictionaryCreateMutable_trampoline_addr, uintptr(allocator), uintptr(capacity), uintptr(unsafe.Pointer(keyCallBacks)), uintptr(unsafe.Pointer(valueCallBacks)))
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(keyCallBacks)
	runtime.KeepAlive(valueCallBacks)
	return CFMutableDictionaryRef(r0)
}

var _mkcgo_CFDictionarySetValue_trampoline_addr uintptr

func CFDictionarySetValue(theDict CFMutableDictionaryRef, key unsafe.Pointer, value unsafe.Pointer) {
	syscallN(_mkcgo_CFDictionarySetValue_trampoline_addr, uintptr(theDict), uintptr(key), uintptr(value))
	runtime.KeepAlive(theDict)
}

var _mkcgo_CFErrorCopyDescription_trampoline_addr uintptr

func CFErrorCopyDescription(__error CFErrorRef) CFStringRef {
	r0, _, _ := syscallN(_mkcgo_CFErrorCopyDescription_trampoline_addr, uintptr(__error))
	runtime.KeepAlive(__error)
	return CFStringRef(r0)
}

var _mkcgo_CFErrorGetCode_trampoline_addr uintptr

func CFErrorGetCode(__error CFErrorRef) CFIndex {
	r0, _, _ := syscallN(_mkcgo_CFErrorGetCode_trampoline_addr, uintptr(__error))
	runtime.KeepAlive(__error)
	return CFIndex(r0)
}

var _mkcgo_CFNumberCreate_trampoline_addr uintptr

func CFNumberCreate(allocator CFAllocatorRef, theType CFNumberType, valuePtr unsafe.Pointer) CFNumberRef {
	r0, _, _ := syscallN(_mkcgo_CFNumberCreate_trampoline_addr, uintptr(allocator), uintptr(theType), uintptr(valuePtr))
	runtime.KeepAlive(allocator)
	return CFNumberRef(r0)
}

var _mkcgo_CFRelease_trampoline_addr uintptr

func CFRelease(cf CFTypeRef) {
	syscallN(_mkcgo_CFRelease_trampoline_addr, uintptr(cf))
	runtime.KeepAlive(cf)
}

var _mkcgo_CFStringGetCStringPtr_trampoline_addr uintptr

func CFStringGetCStringPtr(str CFStringRef, encoding CFStringEncoding) *byte {
	r0, _, _ := syscallN(_mkcgo_CFStringGetCStringPtr_trampoline_addr, uintptr(str), uintptr(encoding))
	runtime.KeepAlive(str)
	return (*byte)(unsafe.Pointer(r0))
}

var _mkcgo_CFStringGetLength_trampoline_addr uintptr

func CFStringGetLength(str CFStringRef) CFIndex {
	r0, _, _ := syscallN(_mkcgo_CFStringGetLength_trampoline_addr, uintptr(str))
	runtime.KeepAlive(str)
	return CFIndex(r0)
}

var _mkcgo_SecKeyCopyExternalRepresentation_trampoline_addr uintptr

func SecKeyCopyExternalRepresentation(key SecKeyRef, __error *CFErrorRef) CFDataRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCopyExternalRepresentation_trampoline_addr, uintptr(key), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(key)
	runtime.KeepAlive(__error)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCopyKeyExchangeResult_trampoline_addr uintptr

func SecKeyCopyKeyExchangeResult(privateKey SecKeyRef, algorithm SecKeyAlgorithm, publicKey SecKeyRef, parameters CFDictionaryRef, __error *CFErrorRef) CFDataRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCopyKeyExchangeResult_trampoline_addr, uintptr(privateKey), uintptr(algorithm), uintptr(publicKey), uintptr(parameters), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(privateKey)
	runtime.KeepAlive(publicKey)
	runtime.KeepAlive(parameters)
	runtime.KeepAlive(__error)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCopyPublicKey_trampoline_addr uintptr

func SecKeyCopyPublicKey(key SecKeyRef) SecKeyRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCopyPublicKey_trampoline_addr, uintptr(key))
	runtime.KeepAlive(key)
	return SecKeyRef(r0)
}

var _mkcgo_SecKeyCreateDecryptedData_trampoline_addr uintptr

func SecKeyCreateDecryptedData(key SecKeyRef, algorithm SecKeyAlgorithm, ciphertext CFDataRef, __error *CFErrorRef) CFDataRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCreateDecryptedData_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(ciphertext), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(key)
	runtime.KeepAlive(ciphertext)
	runtime.KeepAlive(__error)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCreateEncryptedData_trampoline_addr uintptr

func SecKeyCreateEncryptedData(key SecKeyRef, algorithm SecKeyAlgorithm, plaintext CFDataRef, __error *CFErrorRef) CFDataRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCreateEncryptedData_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(plaintext), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(key)
	runtime.KeepAlive(plaintext)
	runtime.KeepAlive(__error)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCreateRandomKey_trampoline_addr uintptr

func SecKeyCreateRandomKey(parameters CFDictionaryRef, __error *CFErrorRef) SecKeyRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCreateRandomKey_trampoline_addr, uintptr(parameters), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(parameters)
	runtime.KeepAlive(__error)
	return SecKeyRef(r0)
}

var _mkcgo_SecKeyCreateSignature_trampoline_addr uintptr

func SecKeyCreateSignature(key SecKeyRef, algorithm SecKeyAlgorithm, data CFDataRef, __error *CFErrorRef) CFDataRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCreateSignature_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(data), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(key)
	runtime.KeepAlive(data)
	runtime.KeepAlive(__error)
	return CFDataRef(r0)
}

var _mkcgo_SecKeyCreateWithData_trampoline_addr uintptr

func SecKeyCreateWithData(keyData CFDataRef, attributes CFDictionaryRef, __error *CFErrorRef) SecKeyRef {
	r0, _, _ := syscallN(_mkcgo_SecKeyCreateWithData_trampoline_addr, uintptr(keyData), uintptr(attributes), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(keyData)
	runtime.KeepAlive(attributes)
	runtime.KeepAlive(__error)
	return SecKeyRef(r0)
}

var _mkcgo_SecKeyGetBlockSize_trampoline_addr uintptr

func SecKeyGetBlockSize(key SecKeyRef) int {
	r0, _, _ := syscallN(_mkcgo_SecKeyGetBlockSize_trampoline_addr, uintptr(key))
	runtime.KeepAlive(key)
	return int(r0)
}

var _mkcgo_SecKeyIsAlgorithmSupported_trampoline_addr uintptr

func SecKeyIsAlgorithmSupported(key SecKeyRef, operation SecKeyOperationType, algorithm SecKeyAlgorithm) Boolean {
	r0, _, _ := syscallN(_mkcgo_SecKeyIsAlgorithmSupported_trampoline_addr, uintptr(key), uintptr(operation), uintptr(algorithm))
	runtime.KeepAlive(key)
	return Boolean(r0)
}

var _mkcgo_SecKeyVerifySignature_trampoline_addr uintptr

func SecKeyVerifySignature(key SecKeyRef, algorithm SecKeyAlgorithm, signedData CFDataRef, signature CFDataRef, __error *CFErrorRef) Boolean {
	r0, _, _ := syscallN(_mkcgo_SecKeyVerifySignature_trampoline_addr, uintptr(key), uintptr(algorithm), uintptr(signedData), uintptr(signature), uintptr(unsafe.Pointer(__error)))
	runtime.KeepAlive(key)
	runtime.KeepAlive(signedData)
	runtime.KeepAlive(signature)
	runtime.KeepAlive(__error)
	return Boolean(r0)
}

var _mkcgo_SecRandomCopyBytes_trampoline_addr uintptr

func SecRandomCopyBytes(rnd SecRandomRef, count int, bytes *byte) int32 {
	r0, _, _ := syscallN(_mkcgo_SecRandomCopyBytes_trampoline_addr, uintptr(rnd), uintptr(count), uintptr(unsafe.Pointer(bytes)))
	runtime.KeepAlive(rnd)
	runtime.KeepAlive(bytes)
	return int32(r0)
}
