// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Code generated by mkcgo. DO NOT EDIT.

#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include "zsecurity.h"

CFDataRef CFDataCreate(CFAllocatorRef, const uint8_t*, CFIndex);
const uint8_t* CFDataGetBytePtr(CFDataRef);
CFIndex CFDataGetLength(CFDataRef);
CFDictionaryRef CFDictionaryCreate(CFAllocatorRef, const void**, const void**, CFIndex, const CFDictionaryKeyCallBacks*, const CFDictionaryValueCallBacks*);
CFMutableDictionaryRef CFDictionaryCreateMutable(CFAllocatorRef, CFIndex, const CFDictionaryKeyCallBacks*, const CFDictionaryValueCallBacks*);
void CFDictionarySetValue(CFMutableDictionaryRef, const void*, const void*);
CFStringRef CFErrorCopyDescription(CFErrorRef);
CFIndex CFErrorGetCode(CFErrorRef);
CFNumberRef CFNumberCreate(CFAllocatorRef, CFNumberType, const void*);
void CFRelease(CFTypeRef);
const char* CFStringGetCStringPtr(CFStringRef, CFStringEncoding);
CFIndex CFStringGetLength(CFStringRef);
CFDataRef SecKeyCopyExternalRepresentation(SecKeyRef, CFErrorRef*);
CFDataRef SecKeyCopyKeyExchangeResult(SecKeyRef, SecKeyAlgorithm, SecKeyRef, CFDictionaryRef, CFErrorRef*);
SecKeyRef SecKeyCopyPublicKey(SecKeyRef);
CFDataRef SecKeyCreateDecryptedData(SecKeyRef, SecKeyAlgorithm, CFDataRef, CFErrorRef*);
CFDataRef SecKeyCreateEncryptedData(SecKeyRef, SecKeyAlgorithm, CFDataRef, CFErrorRef*);
SecKeyRef SecKeyCreateRandomKey(CFDictionaryRef, CFErrorRef*);
CFDataRef SecKeyCreateSignature(SecKeyRef, SecKeyAlgorithm, CFDataRef, CFErrorRef*);
SecKeyRef SecKeyCreateWithData(CFDataRef, CFDictionaryRef, CFErrorRef*);
size_t SecKeyGetBlockSize(SecKeyRef);
Boolean SecKeyIsAlgorithmSupported(SecKeyRef, SecKeyOperationType, SecKeyAlgorithm);
Boolean SecKeyVerifySignature(SecKeyRef, SecKeyAlgorithm, CFDataRef, CFDataRef, CFErrorRef*);
int SecRandomCopyBytes(SecRandomRef, size_t, void*);

CFDataRef _mkcgo_CFDataCreate(CFAllocatorRef _arg0, const uint8_t* _arg1, CFIndex _arg2) {
	return CFDataCreate(_arg0, _arg1, _arg2);
}

const uint8_t* _mkcgo_CFDataGetBytePtr(CFDataRef _arg0) {
	return CFDataGetBytePtr(_arg0);
}

CFIndex _mkcgo_CFDataGetLength(CFDataRef _arg0) {
	return CFDataGetLength(_arg0);
}

CFDictionaryRef _mkcgo_CFDictionaryCreate(CFAllocatorRef _arg0, const void** _arg1, const void** _arg2, CFIndex _arg3, const CFDictionaryKeyCallBacks* _arg4, const CFDictionaryValueCallBacks* _arg5) {
	return CFDictionaryCreate(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

CFMutableDictionaryRef _mkcgo_CFDictionaryCreateMutable(CFAllocatorRef _arg0, CFIndex _arg1, const CFDictionaryKeyCallBacks* _arg2, const CFDictionaryValueCallBacks* _arg3) {
	return CFDictionaryCreateMutable(_arg0, _arg1, _arg2, _arg3);
}

void _mkcgo_CFDictionarySetValue(CFMutableDictionaryRef _arg0, const void* _arg1, const void* _arg2) {
	CFDictionarySetValue(_arg0, _arg1, _arg2);
}

CFStringRef _mkcgo_CFErrorCopyDescription(CFErrorRef _arg0) {
	return CFErrorCopyDescription(_arg0);
}

CFIndex _mkcgo_CFErrorGetCode(CFErrorRef _arg0) {
	return CFErrorGetCode(_arg0);
}

CFNumberRef _mkcgo_CFNumberCreate(CFAllocatorRef _arg0, CFNumberType _arg1, const void* _arg2) {
	return CFNumberCreate(_arg0, _arg1, _arg2);
}

void _mkcgo_CFRelease(CFTypeRef _arg0) {
	CFRelease(_arg0);
}

const char* _mkcgo_CFStringGetCStringPtr(CFStringRef _arg0, CFStringEncoding _arg1) {
	return CFStringGetCStringPtr(_arg0, _arg1);
}

CFIndex _mkcgo_CFStringGetLength(CFStringRef _arg0) {
	return CFStringGetLength(_arg0);
}

CFDataRef _mkcgo_SecKeyCopyExternalRepresentation(SecKeyRef _arg0, CFErrorRef* _arg1) {
	return SecKeyCopyExternalRepresentation(_arg0, _arg1);
}

CFDataRef _mkcgo_SecKeyCopyKeyExchangeResult(SecKeyRef _arg0, SecKeyAlgorithm _arg1, SecKeyRef _arg2, CFDictionaryRef _arg3, CFErrorRef* _arg4) {
	return SecKeyCopyKeyExchangeResult(_arg0, _arg1, _arg2, _arg3, _arg4);
}

SecKeyRef _mkcgo_SecKeyCopyPublicKey(SecKeyRef _arg0) {
	return SecKeyCopyPublicKey(_arg0);
}

CFDataRef _mkcgo_SecKeyCreateDecryptedData(SecKeyRef _arg0, SecKeyAlgorithm _arg1, CFDataRef _arg2, CFErrorRef* _arg3) {
	return SecKeyCreateDecryptedData(_arg0, _arg1, _arg2, _arg3);
}

CFDataRef _mkcgo_SecKeyCreateEncryptedData(SecKeyRef _arg0, SecKeyAlgorithm _arg1, CFDataRef _arg2, CFErrorRef* _arg3) {
	return SecKeyCreateEncryptedData(_arg0, _arg1, _arg2, _arg3);
}

SecKeyRef _mkcgo_SecKeyCreateRandomKey(CFDictionaryRef _arg0, CFErrorRef* _arg1) {
	return SecKeyCreateRandomKey(_arg0, _arg1);
}

CFDataRef _mkcgo_SecKeyCreateSignature(SecKeyRef _arg0, SecKeyAlgorithm _arg1, CFDataRef _arg2, CFErrorRef* _arg3) {
	return SecKeyCreateSignature(_arg0, _arg1, _arg2, _arg3);
}

SecKeyRef _mkcgo_SecKeyCreateWithData(CFDataRef _arg0, CFDictionaryRef _arg1, CFErrorRef* _arg2) {
	return SecKeyCreateWithData(_arg0, _arg1, _arg2);
}

size_t _mkcgo_SecKeyGetBlockSize(SecKeyRef _arg0) {
	return SecKeyGetBlockSize(_arg0);
}

Boolean _mkcgo_SecKeyIsAlgorithmSupported(SecKeyRef _arg0, SecKeyOperationType _arg1, SecKeyAlgorithm _arg2) {
	return SecKeyIsAlgorithmSupported(_arg0, _arg1, _arg2);
}

Boolean _mkcgo_SecKeyVerifySignature(SecKeyRef _arg0, SecKeyAlgorithm _arg1, CFDataRef _arg2, CFDataRef _arg3, CFErrorRef* _arg4) {
	return SecKeyVerifySignature(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int _mkcgo_SecRandomCopyBytes(SecRandomRef _arg0, size_t _arg1, void* _arg2) {
	return SecRandomCopyBytes(_arg0, _arg1, _arg2);
}

