# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MS_GO_NOSYSTEMCRYPTO: "1" # Don't use systemcrypto for testing parity with stdlib

name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25, 1.26]
        macos-version: [macos-14, macos-15, macos-15-intel, macos-26]
        cgo: [0, 1]
        linkmode: ["internal", "external"]
        exclude:
          # CGO_ENABLED=0 is not supported prior to Go 1.26
          - go-version: 1.25
            cgo: 0
          # internal linking is not supported prior to Go 1.26
          - go-version: 1.25
            linkmode: "internal"
          # external linking is not supported with CGO_ENABLED=0
          - linkmode: "external"
            cgo: 0
    runs-on: ${{ matrix.macos-version }}
    steps:
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version }}
          go-download-base-url: "https://aka.ms/golang/release/latest"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Go Tests
        run: CGO_ENABLED=${{ matrix.cgo }} go test -gcflags=all=-d=checkptr -ldflags=-linkmode=${{ matrix.linkmode }} -count 10 -shuffle on -v ./...

      - name: Select Xcode 26.4
        if: matrix.macos-version == 'macos-26'
        run: sudo xcode-select -s /Applications/Xcode_26.4.app

      - name: Run Swift Tests
        if: matrix.macos-version == 'macos-26'
        working-directory: cryptokit
        run: swift test

  linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26"
          go-download-base-url: "https://aka.ms/golang/release/latest"

      - name: Run Build
        run: go build ./...

      - name: Run Build (cgoless)
        run: CGO_ENABLED=0 go build ./...

  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26"
          go-download-base-url: "https://aka.ms/golang/release/latest"

      - name: Run Build for ARM32
        run: |
          GOARCH=arm go build ./...

      - name: Run Build for ARM32 (cgoless)
        run: |
          CGO_ENABLED=0 GOARCH=arm go build ./...

  check-headers:
    strategy:
      fail-fast: false
      matrix:
        macos-version: [macos-14, macos-15, macos-15-intel, macos-26]
    runs-on: ${{ matrix.macos-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26"
          go-download-base-url: "https://aka.ms/golang/release/latest"

      - name: Run go generate
        run: |
          go generate ./...

      - name: Check for any changed files
        run: |
          git diff --exit-code || (echo "Generated files are out of date. Please run 'go generate'." && exit 1)

  conclusion:
    needs:
      - test
      - linux-x64
      - linux-arm
      - check-headers
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Result
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled."
            exit 1
          fi
          echo "All jobs passed."
